apiVersion: apps/v1
kind: Deployment
medatata:
  name: nginx-deployment
  namespase: flux-system
spec:
  selector:
    matchlabels:
      app: nginx
    replicas: 2
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx:alpine
          ports:
          - containerPort: 80
