apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nginx-deployment"
  namespace: "nginx"
spec:
  selector:
    matchLabels:
      app: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: "nginx"
    spec:
      containers:
      - image: nginx:1.24.0
        imagePullPolicy: Always
        name: "nginx"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: nginx-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  index.html |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello, I'm Borislava!</title>
    </head>
    <body>
      <h1>I made it !</h1>
    </body>
    </html>
