apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ./charts/ingress-nginx
      version: "4.2.5"
      sourceRef:
        kind: GitRepository
        name: nginx
  values:
    image:
      chroot: false
      registry: registry.k8s.io
      image: ingress-nginx/controller
      tag: "v1.3.1"
      pullPolicy: IfNotPresent
    ingressClassResource:
      name: nginx
      enabled: true
      default: true
      controllerValue: "k8s.io/nginx-controller"
    ingressClass: nginx
    tolerations:
      - operator: Exists
